challenge/urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView
from challenge.models import Challenge
from challenge.views import ChallengeListViewRecent, ChallengeListViewBounty, ChallengeListViewVotes, ChallengeListViewOldestUnsolved, ChallengeListViewLibrary
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    (r'^$|^popular/?$',
     login_required(ChallengeListViewVotes.as_view())),
    (r'^top-bounty/?$',
     login_required(ChallengeListViewBounty.as_view())),
    (r'^recent/?$',
     login_required(ChallengeListViewRecent.as_view())),
    (r'^oldest-unsolved/?$',
     login_required(ChallengeListViewOldestUnsolved.as_view())),
    (r'^library/?$',
     login_required(ChallengeListViewLibrary.as_view())),
    (r'^tags/$',
        'challenge.views.tags'),
    (r'^tag/(?P<tag>[-_A-Za-z0-9]+)/$',
        'challenge.views.with_tag', {"sortOrder" : "most-recent"}),
    (r'^tag/(?P<tag>[-_A-Za-z0-9]+)/(?P<sortOrder>[-_A-Za-z0-9]+)/$',
        'challenge.views.with_tag'),
    (r'^(?P<slug>[-_A-Za-z0-9]+)/hints$',
        login_required(DetailView.as_view(
            model=Challenge,
            template_name='challenge_hints.html'))),
    (r'^(?P<slug>[-_A-Za-z0-9]+)/talk$',
        login_required(DetailView.as_view(
            model=Challenge,
            template_name='challenge_discussion.html'))),
    (r'^(?P<slug>[-_A-Za-z0-9]+)/solved$',
        login_required(DetailView.as_view(
            model=Challenge,
            template_name='challenge_solved.html'))),
    (r'^(?P<slug>[-_A-Za-z0-9]+)/$',
            login_required(DetailView.as_view(
                model=Challenge,
                template_name='challenge_detail.html')))

)

urls.py
# This also imports the include function
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import TemplateView
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'challenge.views.home_view'),
    (r'^challenge/?', include('challenge.urls')),
    (r'^api/', include('api.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^bench/?', include('bench.urls')),
    (r'^tutorial/?', 'challenge.views.tutorial'),
    (r'^submitEmail/', 'challenge.views.submitEmail'),
    (r'^logout/', 'challenge.views.logout_view'),
    (r'^login/', 'challenge.views.login_view'),
    (r'^about/', 'challenge.views.about_view'),
    (r'^contact/', 'challenge.views.contact_view'),
    (r'^thanks/', 'challenge.views.thanks_view'),
    url(r'^admin/', include(admin.site.urls)),
    )

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

challenge/models.py
from django.db import models
from tagging.fields import TagField
from tagging.models import Tag
from django.contrib.auth.models import User
from django import forms

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    url = models.URLField()
    active_user = models.BooleanField()
    profile_desc = models.CharField(max_length=500)
    cumulative_votes = models.IntegerField(default=0)
    cumulative_bounty = models.IntegerField(default=0)
    current_votes = models.IntegerField(default=0)
    current_bounty = models.IntegerField(default=0)
#    profile_pic = models.ImageField(default="{{ STATIC_URL }}img/profpic.png")
    
    def __unicode__(self):
        return self.user.username

    def get_absolute_url(self):
        return ('profiles_profile_detail', (), { 'username': self.user.username })
    get_absolute_url = models.permalink(get_absolute_url)

    #TODO add photo to user profile
    #TODO add achievements to user profile
    #TODO Extract User functions to their own app
    #TODO Add function to debit/credit votes & bounties

class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    company = forms.CharField()

class SourceSink(models.Model):
    name = models.CharField(max_length=200)
    quantity = models.FloatField(default=0)

    def __unicode__(self):
        return self.name

class Environment(models.Model):
    name = models.CharField(max_length=200)
    temp = models.FloatField(default=37.0)
    pH = models.FloatField(default=7.0)
    sources_and_sinks = models.ManyToManyField(SourceSink)

    def __unicode__(self):
        return self.name

LICENSING_CHOICES = (
    ('ATNC', 'Attribution-NonCommercial'),
    ('ATTR', 'Attribution'),
    ('ALL', 'All-Rights-Reserved'),
)

CHALLENGE_TYPE_CHOICES = (
    ('Energy', 'Renewable energy'),
    ('Food', 'Better food'),
    ('Health', 'Saving lives'),
    ('Environmental', 'Environmental'),
    ('Industrial', 'Industrial'),
    ('Basics', 'Foundational techniques'),
    ('Tutorial', 'Tutorial'),
)

class Challenge(models.Model):
        name = models.CharField(max_length=200)
        challenge_type = models.CharField(max_length=50, choices=CHALLENGE_TYPE_CHOICES, default='Basics')
        image = models.ImageField(upload_to="uploads/", default='biofuel.png')
        slug = models.SlugField(max_length=200)
        descrip = models.TextField()
        tags = TagField()
        sponsor = models.ForeignKey(UserProfile)
        create_date = models.DateTimeField(auto_now=True)
        first_completed = models.DateTimeField('First solved', null=True)
        votes = models.IntegerField()
        bounty = models.DecimalField(max_digits = 10, decimal_places=2)
        chassis = models.CharField(max_length=50, default="e coli")
        environment = models.ForeignKey(Environment, default='2')
        sharing_choice = models.CharField(max_length=24, choices=LICENSING_CHOICES, default='ATNC')

        def __unicode__(self):
            return self.name
        def bounty_avail(self):
            return not self.first_completed
        def get_tags(self):
            return Tag.objects.get_for_object(self)
#        def save(self):
#            if not self.id:
#                self.create_date = datetime.now()
#                super(Challenge, self).save()


    #TODO: Define Criteria as a testable assertion
class Criteria(models.Model):
    challenge = models.ForeignKey(Challenge, related_name='winning_conditions')
    desc = models.CharField(max_length=200)
    status = models.BooleanField()

    def __unicode__(self):
        return self.desc

class Useful_Link(models.Model):
    challenge = models.ForeignKey(Challenge)
    desc = models.CharField(max_length=100)
    url = models.URLField()

    def __unicode__(self):
        return self.desc

class Useful_Component(models.Model):
    challenge = models.ForeignKey(Challenge)
    desc = models.CharField(max_length=100)
    url = models.URLField()

    def __unicode__(self):
        return self.desc

challenge/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    sender = forms.EmailField()
    subject = forms.CharField(max_length=100)
    message = forms.CharField(max_length=5000)

challenge/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404, redirect
from challenge.models import Challenge
from challenge.forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.core.urlresolvers import reverse
from tagging.models import Tag, TaggedItem
from django.views.generic import ListView
import models

def submitEmail(request):
    errors = []
    if request.method == 'POST':
        if request.POST.get('email') and '@' not in request.POST['email']:
            errors.append('Enter a valid e-mail address.')
        if not errors:
            try:
                send_mail('New tyger contact',
                request.POST.get('email'),
                'noreply@tyger.us',
                ['togilvie@tyger.us'],
            )
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            errors.append("Thanks - we'll keep you up to date!")
            return HttpResponseRedirect('/')
    return render_to_response('index_splash.html',
        {'msg': errors})

def home_view(request):
        return render_to_response('index_splash.html',
        context_instance=RequestContext(request))

@login_required()
def tags(request):
        return render_to_response('challenges_tag_cloud.html',
        context_instance=RequestContext(request))

@login_required()
def with_tag(request, tag, sortOrder, object_id=None, page=1):
    query_tag = Tag.objects.get(name=tag)
    tagged_challenges = TaggedItem.objects.get_by_model(models.Challenge, query_tag)
    if sortOrder == "most-recent":
        tagged_challenges = tagged_challenges.order_by('-create_date')
    elif sortOrder == "top-bounty":
        tagged_challenges = tagged_challenges.order_by('-bounty')
    elif sortOrder == "top-votes":
        tagged_challenges = tagged_challenges.order_by('-votes')
    elif sortOrder == "oldest-unsolved":
        tagged_challenges = tagged_challenges.filter(first_completed__isnull=True).order_by('create_date')
    elif sortOrder == "library":
        tagged_challenges = tagged_challenges.filter(sponsor__user__username='tygerlibrary').order_by('-create_date')
    return render_to_response('challenge_with_tag.html',
                              dict(tag=tag, tagged_challenges=tagged_challenges, sortOrder=sortOrder),
                              context_instance=RequestContext(request))

# Tutorial view looks for all challenges tagged with "tutorial"
@login_required()
def tutorial(request):
    tag = "tutorial"
    tagged_challenges = TaggedItem.objects.get_by_model(models.Challenge, tag)
    tagged_challenges = tagged_challenges.order_by('create_date')
    return render_to_response('challenge_tutorial.html',
                              dict(tag=tag, tagged_challenges=tagged_challenges),
                              context_instance=RequestContext(request))

#TODO: Hacked this into multiple views to handle sorting. Should be slicker
class ChallengeListViewRecent(ListView):
    context_object_name = "top25_challenge_list"
    template_name='challenge_list.html'
    queryset = Challenge.objects.order_by('-create_date')[:25]

    def get_context_data(self, **kwargs):
        context = super(ChallengeListViewRecent, self).get_context_data(**kwargs)
        context['sortOrder'] = "most-recent"
        context['request'] = self.request
        return context

class ChallengeListViewBounty(ListView):
    context_object_name = "top25_challenge_list"
    template_name='challenge_list.html'
    queryset = Challenge.objects.order_by('-bounty')[:25]

    def get_context_data(self, **kwargs):
        context = super(ChallengeListViewBounty, self).get_context_data(**kwargs)
        context['sortOrder'] = "top-bounty"
        context['request'] = self.request
        return context

class ChallengeListViewVotes(ListView):
    context_object_name = "top25_challenge_list"
    template_name='challenge_list.html'
    queryset = Challenge.objects.order_by('-votes')[:25]

    def get_context_data(self, **kwargs):
        context = super(ChallengeListViewVotes, self).get_context_data(**kwargs)
        context['sortOrder'] = "top-votes"
        context['request'] = self.request
        return context

class ChallengeListViewOldestUnsolved(ListView):
    context_object_name = "top25_challenge_list"
    template_name='challenge_list.html'
    queryset = Challenge.objects.filter(first_completed__isnull=True).order_by('create_date')[:25]

    def get_context_data(self, **kwargs):
        context = super(ChallengeListViewOldestUnsolved, self).get_context_data(**kwargs)
        context['sortOrder'] = "oldest-unsolved"
        context['request'] = self.request
        return context

class ChallengeListViewLibrary(ListView):
    context_object_name = "top25_challenge_list"
    template_name='challenge_list.html'
    queryset = Challenge.objects.filter(sponsor__user__username='tyger-library').order_by('-create_date')[:25]

    def get_context_data(self, **kwargs):
        context = super(ChallengeListViewLibrary, self).get_context_data(**kwargs)
        context['sortOrder'] = "library"
        context['request'] = self.request
        return context

@login_required()
def logout_view(request):
    logout(request)
    return redirect('/login/')

def login_view(request):
    state = "Sign In"
    username = password = ''
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/challenge/')
            else:
                state = "Account is not active, please contact the site admin."
        else:
            state = "Username and/or password were incorrect."

    return render_to_response('auth.html',{'state':state, 'username': username}, context_instance=RequestContext(request))

@login_required()
def about_view(request):
    
        return render_to_response('about.html',context_instance=RequestContext(request))

@login_required()
def contact_view(request):
    if request.method == 'POST': # If the form has been submitted...
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            name = form.cleaned_data['name']
            sender = form.cleaned_data['sender']
            recipients = ['me@timogilvie.com']
            send_mail(subject, message, name, sender, recipients)
            return HttpResponseRedirect('/thanks/') # Redirect after valid POST
    else:
        form = ContactForm() # Display empty form

    return render_to_response('contact.html', {
        'form': form,
    }, context_instance=RequestContext(request))

@login_required()
def thanks_view(request):
    
        return render_to_response('thanks.html',context_instance=RequestContext(request))

challenge/templates/about.html
{% extends 'challenge_base.html' %}

{% block title %} About Tyger {% endblock %}

    {% block content %}

   <h2>About Tyger</h2>
   <div>
        <p>We believe synthetic biology will transform the 21st century and we wanted to start hacking. But we didn't have easy access to a PCR machine and all the other fancy (read: expensive) lab technology to get our hands dirty. So we built a platform to make it easy for hackers to design new life without being in a lab. That's the Bench. </p>
        <p>Then we wanted some big ideas to work on. We want to save a billion lives, send humanity to the stars, and all sorts of other projects that sound like science fiction but are very close to our grasp. But the biggest ideas are spread all across the community and not always obvious. So we created the Challenge system to help the best ideas bubble to the top and connect users to cool projects that can change the world.  </p>
   </div>

   <h3> What's with the name? Can't you spell tiger? </h3>
   <div>
       <p>Our name comes from William Blake's poem <a href="http://www.eecs.harvard.edu/~keith/poems/tyger.html">The Tyger</a>.
           Blake uses the fearful Tyger to represent the world's evils and questions a creator that would allow such evils to stalk the world.</p>
       <p>Modern evils are no less fearful. Millions die from hunger or preventable disease. Global extinction events are real possibilities. We believe synthetic biology offers answers to these problems. </p>
       <p>We are looking for hands that "dare seize the fire", as the Titan Prometheus did when he stole fire from the gods to help humanity. Will you dare the same to help the world?  Tyger wants to help coordinate those who want to use synthetic biology to change the world for the better. If you're interested, get involved!</p>
   </div>

        <h3> Work for Tyger </h3>

   <div>
        <ul>We're looking for smart people who want to change the world:
            <li>Technical experts: We use HTML5, javascript, python, django, backbone.js and a variety of other standard web tools. Great candidates will be intimately familiar with one or more of these technologies. We can teach you the synthetic biology.
            <li>Bio-hackers: We need synthetic biologists who have experience designing new life. You'll help design our software and work challenge sponsors to ensure that the challenges they sponsor are successful.
            <li>Hustlers: We need very exceptional business people to spread our message to our customers and users.
        </ul>
    </div>

{% endblock content %}

challenge/templates/base_challenge.html
{% extends 'base.html' %}

{% block title %} Tyger | Solving Synthetic Biology's Most Important Challenges{% endblock title %}

{% block header %}
    <div class="container">
        <div class="span-8 append-1">
            <div id="title">
                <h1 id="logo"><a href ="/challenge">Tyger</a></h1>
            </div>
        </div>
        <div class="span-15 last">
            <div id="nav">
                <ul class="side">
                    <li><a class="current" href="/challenge/">Challenges</a></li>
                    <li><a href="/bench/">Bench</a></li>
                    <li><a href="/tutorial/">Tutorial</a></li>
                    {% include "profiles/user_insert.html" %}
                </ul>
            </div>
        </div>
    </div>
{%  endblock header %}

{% block content %}
    <div class="container">
        <div id="main-wrapper" class="span-17"> 
            <div class="content-box clearfix">
                <div class="challenge-title" class="span-17 last"> 
                    <span class="column last" style="border-bottom:1px solid #ddd;width:619px;box-shadow:white 0 1px 0;">
                        <span class="column">
                            {% block sub-header %}<h1>Challenges</h1> {% endblock sub-header %}
                        </span>
                        <span class="column last" style="float:right">
                            {% block sort-header %}
                            {% endblock sort-header %}
                        </span>
                    </span>
                </div>

                <div id="challenge-listings" class="span-17 last">
                    <div id="listings">
                        {% block listings %}
                        {% endblock listings%}
                    </div>
                </div>
            </div>
        </div>

        <div id="sidebar-wrapper" class="span-6 last" style="float:right"> 
            {% block sidebar %}
            {% endblock sidebar %}
        </div>
    </div>

{% endblock content %}

challenge/templates/challenge_base.html
{% extends 'base.html' %}

{% block title %} Tyger | Solving Synthetic Biology's Most Important Challenges{% endblock title %}

{% block content %}
    {% block sub_header %}
    <div id="sub-header">
        <div class="container">
            <span class="column">
                <span class="ico-challenge"></span>
            </span>
            <span class="column last">
                <h1>Challenges</h1> 
                <h2>Solving Synthetic Biology's Most Important Challenges.</h2>
            </span>
            <span id="challenges-metrics" class="column right last">
                <span class="column">
                    28
                    <div class="label">Open Challenges</div>
                </span>
                <span class="column last">
                    $18,300
                    <div class="label">Available bounties</div>
                </span>
            </span>
        </div>
    </div>
    {% endblock sub_header %}

    {% block container %}
    <div class="container">
        <div id="content-wrapper" class="span-{% block content_span %}20{% endblock content_span %}">
            {% block content_header %} {% endblock %}
            {% block challenge_content %} {% endblock %}
        </div>
        {% block sidebar %}
        <div id="sidebar-wrapper" class="span-{% block sidebar_span %}4{% endblock sidebar_span %} last">
            <div class="sidebar">
            </div>
        </div>
        {% endblock sidebar %}
    </div>
    {% endblock container %}

{% endblock content %}

challenge/templates/challenge_detail.html
{% extends 'challenge_base.html' %}

{% block title %} {{ challenge.name|capfirst}} | Tyger {% endblock title %}


{% block sub_header %}
    <div class="clearfix">
        <span class="column" style=""> 
            <h1 style="font-size:20px;line-height:40px">{{ challenge.name|capfirst}}</h1>
        </span>    
    </div>

    <div class="column clearfix">
        <ul class="tabs">
            <li class="current"><a href="#">Summary</a></li>
            <li><a href="#">References</a></li>
            <li><a href="#">Discussion</a></li>
            <li><a href="#">Solutions</a></li>
        </ul>
    </div>
    <div class="column last right clearfix">
        <span class="column last right tright">
            <button class="btn primary no-margin">Submit Solution</button>
            <button class="btn no-margin">Watch</button>
        </span>
    </div>
{% endblock sub_header %}

{% block content_span %}18{% endblock content_span %}
{% block sidebar_span %}6{% endblock sidebar_span %}
{% block challenge_content %}
    <div class="challenge-detail">
        <div class="challenge-tags tright">
            <span class="ico-tag"></span>
            <span style="margin-left:10px">
                {% for t in challenge.get_tags %}
                    <a class="tag">{{t}}</a>
                {% endfor %}
            </span>
        </div>

        <div class="challenge-description">
            <h3>Description </h3>
            <p>{{ challenge.descrip }} </p>
        </div>

        <div class="row clearfix" style="border-bottom:1px dashed #ddd;margin-bottom:10px">
            <div class="challenge-winconditions">
                <h3> Winning conditions </h3>
                <ul>
                    {% for condition in challenge.criteria_set.all %}
                        <li class="{% if condition.status == "True" %} complete {% endif %}">{{ condition.desc }}</li>
                    {% endfor %}
                </ul>      
            </div>
        </div>
        <div class="row clearfix" style="border-bottom:1px dashed #ddd;margin-bottom:10px">
            <div class="challenge-environment">
                <h3>Environment </h3>
                    <div class="table">
                        <div class="row clearfix">
                            <div class="column key">Chassis</div>
                            <div class="column value last">{{ challenge.chassis }}</div>
                        </div>
                        <div class="row clearfix">
                            <div class="column key">Environment</div>
                            <div class="column value last">{{ challenge.environment.name }}</div>
                        </div>
                        <div class="row clearfix">
                            <div class="column key">Temperature</div>
                            <div class="column value last">{{ challenge.environment.temp }}</div>
                        </div>
                        <div class="row clearfix">
                            <div class="column key">pH</div>
                            <div class="column value last">{{ challenge.environment.pH }}</div>
                        </div>
                    </div> 
            </div>
        </div>

        <div class="row clearfix">
            <div class="challenge-components column" style="width:50%">
                <h3> Useful components </h3>
                <ul>
                    {% for link in challenge.useful_component_set.all %}
                        <li><a href="{{ link.url }}">{{ link.desc }}</a></li>
                    {% endfor %}
                </ul>
            </div>


            <div class="challenge-references column last">
                <h3> References</h3>
                <ul>
                    {% for ref in challenge.useful_link_set.all %}
                        <li><a href="{{ ref.url }}">{{ ref.desc }}</a></li>
                    {% endfor %}
                </ul>       
            </div>
        </div>

        <div id="disqus_thread"></div>
        <script type="text/javascript">
        var disqus_shortname = 'tyger';
        var disqus_developer = 1;
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">synthetic bio comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>
{% endblock challenge_content %}

{% block sidebar %}
    {% load date_diff %}

    <div class="challenge-rewards">
        <div class="challenge-bounty">
            {% if challenge.bounty_avail %}
                <div class="bounty thick">
                    ${{ challenge.bounty }}
                </div>
                <div class="label">Bounty</div>
            {% else %} 
                <h4>Bounty Claimed</h4>
            {% endif %}
        </div>
        <div class="challenge-votes">
            <div class="clearfix">
                <div class="column">
                    <div class="thick">{{ challenge.votes }}</div>
                    <div class="label">Votes</div>
                </div>
                <div class="column last">
                    <button class="btn" style="margin:0;padding:8px"><span class="ico-promote-btn"></span> &nbsp;Promote</button>
                </div>
            </div>
        </div>
    </div>
    <div class="challenge-info">
        <div class="row" style="margin-bottom:10px">
            <div class="label">Sponsored By</div>
            <div>{{ challenge.sponsor.user.username }}</div>
        </div>
        <div class="row">
            <div class="label">Created</div>
            <div>{{ challenge.create_date|date_diff }}</div>
        </div>
    </div>
{%  endblock sidebar %}

challenge/templates/challenge_discussion.html
{% extends 'challenge_detail.html' %}

{% block title %} Discuss solving {{ challenge.name|capfirst}}{% endblock title %}

{% block sub_header %}
<div id="sub-header">
    <div class="container">
        <span class="column">
            <span class="ico-challenge"></span>
        </span>
        <span class="column last">
            <h1>Discussion for {{ challenge.name|capfirst}}</h1>
            <div class="column clearfix">
                <ul class="tabs">
                    <li><a href=".">Description</a></li>
                    <li><a href="hints">Helpful Hints</a></li>
                    <li class="current"><a href="">Discussion</a></li>
                    <li><a href="solved">Solutions</a></li>
                </ul>
            </div>
        </span>
        <span id="challenges-metrics" class="column right last">
            <span class="column last right tright">
                <button class="btn primary no-margin">Submit Solution</button>
                <button class="btn no-margin">Watch</button>
            </span>
        </span>
    </div>
</div>
{% endblock sub_header %}

{% block content_span %}18{% endblock content_span %}
{% block sidebar_span %}6{% endblock sidebar_span %}
{% block challenge_content %}

        <div class="row clearfix" style="border-bottom:1px dashed #ddd;margin-bottom:10px">

        <div id="disqus_thread"></div>
        <script type="text/javascript">
        var disqus_shortname = 'tyger';
        var disqus_developer = 1;
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">synthetic bio comments powered by <span class="logo-disqus">Disqus</span></a>
        </div>
{% endblock challenge_content %}

challenge/templates/challenge_hints.html
{% extends 'challenge_detail.html' %}

{% block title %} Hints for {{ challenge.name|capfirst}} {% endblock title %}

{% block sub_header %}
<div id="sub-header">
    <div class="container">
        <span class="column">
            <span class="ico-challenge"></span>
        </span>
        <span class="column last">
            <h1>Hints for {{ challenge.name|capfirst}}</h1>
            <div class="column clearfix">
                <ul class="tabs">
                    <li><a href=".">Description</a></li>
                    <li class="current"><a href="">Helpful Hints</a></li>
                    <li><a href="talk">Discussion</a></li>
                    <li><a href="solved">Solutions</a></li>
                </ul>
            </div>
        </span>
        <span id="challenges-metrics" class="column right last">
            <span class="column last right tright">
                <button class="btn primary no-margin">Submit Solution</button>
                <button class="btn no-margin">Watch</button>
            </span>
        </span>
    </div>
</div>
{% endblock sub_header %}

{% block content_span %}18{% endblock content_span %}
{% block sidebar_span %}6{% endblock sidebar_span %}
{% block challenge_content %}
        <div class="row clearfix">
            <div class="challenge-components column" style="width:50%">
                <h3> Recommended components </h3>
                <ul>
                    {% for link in challenge.useful_component_set.all %}
                        <li><a href="{{ link.url }}">{{ link.desc }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="challenge-references column last">
                <h3> Recommended references</h3>
                <ul>
                    {% for ref in challenge.useful_link_set.all %}
                        <li><a href="{{ ref.url }}">{{ ref.desc }}</a></li>
                    {% endfor %}
                </ul>       
            </div>
        </div>
{% endblock challenge_content %}

challenge/templates/challenge_solutions_list.html
{% extends 'challenge_base.html' %}

{% block title %} Solutions submitted to {{ challenge.name }} {% endblock title %}

{% block listings %}
List Solutions to {{ challenge.name }}

    <ul>
    {% for condition in challenge.criteria_set.all %}
        <li>{{condition.desc}} -- {{condition.status}}</li>
    {% endfor %}
    </ul>

<a href='/challenge/{{ challenge.slug }}/'>Submit solution again?</a>
{% endblock listings %}


{% block sidebar %}
{% endblock sidebar %}